#include <stdio.h>
#include <stdlib.h>

#include "../util/str.hpp"

//------------------------------------------------------------------------------
int usage()
{
	printf( "Usage: stringtable <infile> <outfile>\n" );
	return -1;
}

//------------------------------------------------------------------------------
int main( int argn, char *argv[] )
{
	if ( argn != 3 )
	{
		return usage();
	}

	Cstr buffer;
	if ( !buffer.fileToBuffer(argv[1]) )
	{
		printf( "Could not load [%s]\n", argv[1] );
		return usage();
	}

	Cstr defines;
	Cstr strings = "//------------------------------------------------------------------------------\n"
				   "const PROGMEM unsigned char c_stringTable[]=\n{\n";

	Cstr temp;
	unsigned int pos = 0;
	unsigned int offset = 0;

	while( pos < buffer.size() )
	{
		temp.clear();
		for( ;buffer[pos] && pos < buffer.size(); pos++ )
		{
			if ( buffer[pos] == '\n' || buffer[pos] == '\r' )
			{
				break;
			}

			temp += buffer[pos];
		}

		for( pos++; isspace(buffer[pos]); pos++ );

		printf( "[%s]\n", temp.c_str() );

		defines.appendFormat( "#define S%05d %d // \"%s\"\n", offset, offset, temp.c_str() );

		strings.append( "\t" );
		for( unsigned int i=0; i<temp.size(); i++ )
		{
			strings.appendFormat( "%02X, ", (unsigned char)temp[i] );
			offset++;
		}
		strings.append( "0,\n" );
	}

	strings.append( "};\n" );

	temp = "#ifndef STRING_TABLE_H\n"
		   "#define STRING_TABLE_H\n"
		   "/*------------------------------------------------------------------------------*\n"
		   "* Copyright: (c) 2013 by Curt Hartung avr@northarc.com\n"
		   "* This work is released under the Creating Commons 3.0 license\n"
		   "* found at http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode\n"
		   "* and in the LICENCE.txt file included with this distribution\n"
		   "*/\n"
		   "\n"
		   "******************************************************************************\n"
		   "******************************************************************************\n"
		   "********* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT DIRECTLY *********\n"
		   "******************************************************************************\n"
		   "******************************************************************************\n"
		   "\n";

	temp += defines;
	temp += "\n\n";
	temp += strings;
	temp += "\n#endif\n";

	if ( !temp.bufferToFile(argv[2]) )
	{
		printf( "Could not save to [%s]\n", argv[2] );
		return usage();
	}

	return 0;
}